修改工作流

diff --git a/.github/workflows/configtest.yml b/.github/workflows/configtest.yml
--- a/.github/workflows/configtest.yml
+++ b/.github/workflows/configtest.yml
@@ -1,7 +1,7 @@
 # This workflow will build a .NET project
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
 
-name: build and test
+name: 'configCheck'
 
 on:
   push:
@@ -21,7 +21,7 @@ jobs:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [windows-latest]
+        os: [ubuntu-latest]
 
     steps:
     - uses: actions/checkout@v3
@@ -37,4 +37,12 @@ jobs:
       run: dotnet build --configuration Release --no-restore
     
     - name: Test
-      run: dotnet test --no-restore --verbosity normal
+      run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
+
+    - name: Report
+        - uses: actions/upload-artifact@v4  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
+        with:
+          name: config-results
+          reporter: dotnet-trx
+          path: test-results.trx
